name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm ci
          npm run build
      - uses: ./
        id: migrations
        with:
          files: '["migrations/test.sql", "package.json"]'
          pattern: 'migrations'
      - name: Echo output
        run: echo "{{ steps.migrations.outputs.content }}"
