name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          npm ci
          npm run build
      - uses: ./
        id: migrations
        with:
          files: ['migrations/test.sql', 'package.json']
      - name: Echo output
        run: echo ${{ steps.migrations.outputs.content }}
